REQUIRE ffl/tst.fs
REQUIRE generate.fs

." TEST GENERATE" CR
9 TO GAME-LENGTH
T{
    ." can replace a right take" CR
    INIT-WINNING
    GAME GAME-LENGTH S" 000010000" ?STR
    GAME GAME-LENGTH RIGHT-TAKE-P BEFORE-RIGHT-TAKE
    REPLACE-WITH-TAKE
    GAME GAME-LENGTH S" 001100000" ?STR
}T
T{
    ." can replace a left take" CR
    INIT-WINNING
    GAME GAME-LENGTH S" 000010000" ?STR
    GAME GAME-LENGTH LEFT-TAKE-P BEFORE-LEFT-TAKE
    REPLACE-WITH-TAKE
    GAME GAME-LENGTH S" 000001100" ?STR
}T

T{
    ." does nothing when no take found" CR
    S" 111111111" 2DUP LEFT-TAKE-P BEFORE-LEFT-TAKE
    REPLACE-WITH-TAKE
    S" 111111111" ?STR

T{  ." can replace several random takes" CR
    INIT-WINNING
    4807 SEED !
    GAME GAME-LENGTH REPLACE-WITH-RANDOM-TAKES
    GAME GAME-LENGTH S" 101110110" ?STR
}T




