REQUIRE ffl/tst.fs
REQUIRE generate.fs

." TEST GENERATE" CR
9 TO GAME-LENGTH
T{
    ." can replace a right take" CR
    INIT-WINNING
    GAME GAME-LENGTH RIGHT-TAKE-P BEFORE-RIGHT-TAKE
    REPLACE-WITH-TAKE
    GAME GAME-LENGTH TYPE CR
}T
