REQUIRE ffl/tst.fs
REQUIRE generate.fs
REQUIRE loner.fs

." TEST GENERATE" CR
9 TO GAME-LENGTH
T{
    ." can replace a right take" CR
    INIT-WINNING
    GAME GAME-LENGTH S" 000010000" ?STR
    GAME GAME-LENGTH RIGHT-TAKE-P BEFORE-RIGHT-TAKE
    REPLACE-WITH-TAKE
    GAME GAME-LENGTH LONER? ?TRUE
}T
T{
    ." can replace a left take" CR
    INIT-WINNING
    GAME GAME-LENGTH S" 000010000" ?STR
    GAME GAME-LENGTH LEFT-TAKE-P BEFORE-LEFT-TAKE
    REPLACE-WITH-TAKE
    GAME GAME-LENGTH LONER? ?TRUE
}T





