
10000 8 / 1+ CONSTANT /BITSET

H-CREATE BITSET /BITSET H-ALLOT

: BITSET-INIT
    BITSET /BITSET ERASE ;

: BITSET-INCLUDE? ( n -- flag )
    8 /MOD BITSET + @
    1 ROT LSHIFT AND ;

: BITSET-INCLUDE! ( n -- )
    8 /MOD BITSET + DUP @
    ROT 1 SWAP LSHIFT OR SWAP C! ;
