10 CONSTANT NAME-MAX
65521 CONSTANT HASHTABLE-SIZE
256 CONSTANT MAX-LINE
CREATE LINE-BUFFER MAX-LINE ALLOT
VARIABLE HASHTABLE
VARIABLE NAMETABLE
VARIABLE NAMETABLE-MAX

HASHTABLE-SIZE NAME-MAX * ALLOCATE THROW NAMETABLE !
HASHTABLE-SIZE CELLS 2* ALLOCATE THROW HASHTABLE !




: RANK ( c - n )
    [CHAR] a - 1+ ;

: <<RANK ( n,c -- n' )
    RANK SWAP 5 LSHIFT OR ;

: HKEY ( addr,count -- n )
    OVER + SWAP 0 -ROT DO I C@ <<RANK LOOP HASHTABLE-SIZE MOD ;

: READ-LN
    LINE-BUFFER MAX-LINE STDIN READ-LINE THROW ;

: ADD-NAME ( addr,n -- dest )
    NAMETABLE-MAX @ -ROT
    10 MIN DUP >R
    NAMETABLE-MAX @ SWAP CMOVE
    R> NAMETABLE-MAX +! SWAP ;

: MAIN
    NAMETABLE @ NAMETABLE-MAX !
    NAMETABLE @ HASHTABLE-SIZE NAME-MAX * ERASE
    BEGIN
        READ-LN WHILE
        DUP IF
            LINE-BUFFER OVER ADD-NAME
            LINE-BUFFER SWAP HKEY . CR
        ELSE
            EXIT
        THEN
    REPEAT
    HASHTABLE @ FREE THROW
    NAMETABLE @ FREE THROW ;

MAIN BYE
