65536 16 * CONSTANT /HEAP

VARIABLE HEAP-START
VARIABLE HEAP-NEXT

: HEAP-ALLOCATE
    /HEAP ALLOCATE THROW
    HEAP-START ! ;

: HEAP-FREE
    HEAP-START @ FREE THROW ;

: HEAP-INIT
    HEAP-START @ HEAP-NEXT ! ;

: HEAP-HERE ( -- addr )
    HEAP-NEXT @ ;

: HEAP-ALLOT ( n -- ) 
    HEAP-NEXT @ HEAP-START @ - OVER + ASSERT( /HEAP < )
    HEAP-NEXT +! ;

: HEAP-,  ( n -- )
    HEAP-HERE !
    CELL HEAP-NEXT +! ;

: HEAP-C, ( c -- )
    HEAP-HERE C!
    1 HEAP-NEXT +! ;

: INSERT-LINK ( addr, count, link -- link' )
    HEAP-HERE >R
    HEAP-, DUP >R
    HEAP-HERE SWAP CMOVE
    R> HEAP-ALLOT R> ;
    



