REQUIRE ffl/tst.fs
REQUIRE HASH-TABLE.fs

." HASH-TABLE TEST" CR

1048576 HEAP-MEMORY-INIT

T{
4807 s" foo" HASH-INSERT-RECORD
s" foo" HASH-FIND-RECORD ?TRUE 4807 ?S
s" bar" HASH-FIND-RECORD ?FALSE

1 s" furmeyer" HASH-INSERT-RECORD
2 s" mennecy" HASH-INSERT-RECORD 
3 s" salazac" HASH-INSERT-RECORD

s" mennecy" HASH-FIND-RECORD ?TRUE 2 ?S
s" salazac" HASH-FIND-RECORD ?TRUE 3 ?S
s" furmeyer" HASH-FIND-RECORD ?TRUE 1 ?S
}T

HEAP-MEMORY-FREE
