REQUIRE ffl/tst.fs
REQUIRE TEST-HEAP-MEMORY.fs
REQUIRE TEST-HASH-TABLE.fs
REQUIRE TEST-PRIORITY-QUEUE.fs

HEAP-MEMORY-FREE
BYE
REQUIRE test-array.fs
REQUIRE test-heap.fs
REQUIRE test-link.fs
REQUIRE test-hash.fs

BYE

HEAP-ALLOCATE HEAP-INIT
NAMES-INIT
HASH-TABLE-INIT

CREATE TEST-KEYS /HASH-TABLE ALLOT
CREATE TEST-NB-KEYS 100 CELLS ALLOT
CREATE LINE-BUFFER 256 ALLOT

: FILL-TABLE
    S" test/communes.txt" R/O OPEN-FILE THROW
    >R
    BEGIN
        LINE-BUFFER 256 R@ READ-LINE THROW WHILE
        DUP IF
            LINE-BUFFER SWAP HASH-KEY TEST-KEYS + DUP C@ 1+ SWAP C!
        ELSE
            DROP
        THEN
    REPEAT DROP
    R> CLOSE-FILE THROW ;

: .TABLE
    CR
    0 /HASH-TABLE 0 DO TEST-KEYS I + C@ + LOOP
    CR . ." keys" CR
    /HASH-TABLE 0 DO TEST-KEYS I + C@ 10 MIN CELLS TEST-NB-KEYS + 1 SWAP +! LOOP
    CR
    0 11 1 DO I 3 .R ." : " TEST-NB-KEYS I CELLS + @ DUP 6 .R I * + DUP SPACE 6 .R CR LOOP DROP ;

TEST-KEYS /HASH-TABLE ERASE
FILL-TABLE
.TABLE

: INSERT-TABLE
    S" test/communes.txt" R/O OPEN-FILE THROW
    >R
    BEGIN
        LINE-BUFFER 256 R@ READ-LINE THROW WHILE
        ?DUP IF
            LINE-BUFFER SWAP INSERT-RECORD
        THEN
    REPEAT
    R> CLOSE-FILE THROW DROP ;

INSERT-TABLE
S" blogolo" FIND-RECORD 0 ?S
S" amiens" FIND-RECORD DUP RECORD-NAME COUNT S" amiens" ?STR RECORD-INDEX 343 ?S
S" arras" FIND-RECORD DUP RECORD-NAME COUNT S" arras" ?STR RECORD-INDEX 747 ?S
S" parzac" FIND-RECORD DUP RECORD-NAME COUNT S" parzac" ?STR RECORD-INDEX 11703 ?S
S" toulouse" FIND-RECORD DUP RECORD-NAME COUNT S" toulouse" ?STR  RECORD-INDEX 14803 ?S

S" amiens"     FIND-RECORD RECORD-INDEX EDGES DUP DUP 
S" arras"      FIND-RECORD RECORD-INDEX 60 ADD-EDGE
S" abbeville"  FIND-RECORD RECORD-INDEX 30 ADD-EDGE
S" toulouse"   FIND-RECORD RECORD-INDEX 822 ADD-EDGE

S" abbeville"  FIND-RECORD RECORD-INDEX EDGES DUP
S" amiens"     FIND-RECORD RECORD-INDEX 30 ADD-EDGE


CR
: .EDGES
    BEGIN
        ?DUP WHILE
        DUP EDGE SWAP . . CR
        EDGE-LINK
    REPEAT ;

S" abbeville" FIND-RECORD RECORD-INDEX EDGES @ .EDGES

S"    4807" SKIP-SPACE S" 4807" ?STR
S" foo" SKIP-SPACE S" foo" ?STR
S"      " SKIP-SPACE 0 ?S DROP

S" 2317   4807" STR>INT S"    4807" ?STR 2317 ?S 
S"   23   17   42" SKIP-SPACE STR>INT SKIP-SPACE STR>INT SKIP-SPACE STR>INT 2DROP 42 ?S 17 ?S 23 ?S
S" amiens  arras" PAD STR>NAME S"   arras" ?STR PAD COUNT S" amiens" ?STR

QUEUE-INIT
1 4807 INSERT-QUEUE-ITEM

2 2317 INSERT-QUEUE-ITEM
3 9999 INSERT-QUEUE-ITEM
4 0015 INSERT-QUEUE-ITEM
EXTRACT-QUEUE-ITEM SWAP 4 ?S 15 ?S
EXTRACT-QUEUE-ITEM SWAP 2 ?S 2317 ?S
EXTRACT-QUEUE-ITEM SWAP 1 ?S 4807 ?S
EXTRACT-QUEUE-ITEM SWAP 3 ?S 9999 ?S
BITSET-INIT
4807 BITSET-INCLUDE? ?FALSE
4807 BITSET-MARK
4807 BITSET-INCLUDE? ?TRUE
4806 BITSET-INCLUDE? ?FALSE

S" abbeville" FIND-RECORD RECORD-INDEX 
S" toulouse" FIND-RECORD RECORD-INDEX
CR CR
PATH-WEIGHT 852 ?S
S" toulouse" FIND-RECORD RECORD-INDEX
S" abbeville" FIND-RECORD RECORD-INDEX 
CR CR
PATH-WEIGHT 852 ?S
HEAP-FREE

BYE

