REQUIRE ffl/tst.fs
REQUIRE bitset.fs

." test bitset" CR
T{
    BITSET-INIT
    
    4807 INCLUDE? ?FALSE
    4807 INCLUDE!
    4807 INCLUDE? ?TRUE
    4806 INCLUDE? ?FALSE

    MAX-ELEMENTS 1 - INCLUDE? ?FALSE
    MAX-ELEMENTS 1 - INCLUDE!
    MAX-ELEMENTS 1 - INCLUDE? ?TRUE
    BITSET-FREE
}T
