REQUIRE ffl/tst.fs
REQUIRE shpath.fs

HEAP-ALLOCATE HEAP-INIT
4807    0 S" foo" CREATE-RECORD
2317 SWAP S" bar" CREATE-RECORD
DUP RECORD-NAME COUNT S" bar" ?STR
DUP RECORD-INDEX 2317 ?S
RECORD-LINK
DUP RECORD-NAME COUNT S" foo" ?STR
    RECORD-INDEX 4807 ?S

CREATE TEST-KEYS /HASH-TABLE ALLOT
CREATE TEST-NB-KEYS 100 CELLS ALLOT
CREATE LINE-BUFFER 256 ALLOT

: FILL-TABLE
    S" test/communes.txt" R/O OPEN-FILE THROW
    >R
    BEGIN
        LINE-BUFFER 256 R@ READ-LINE THROW WHILE
        DUP IF
            LINE-BUFFER SWAP HASH-KEY TEST-KEYS + DUP C@ 1+ SWAP C!
        ELSE
            DROP
        THEN
    REPEAT DROP
    R> CLOSE-FILE THROW ;

: .TABLE
    CR
    0 /HASH-TABLE 0 DO TEST-KEYS I + C@ + LOOP
    CR . ." keys" CR
    /HASH-TABLE 0 DO TEST-KEYS I + C@ 10 MIN CELLS TEST-NB-KEYS + 1 SWAP +! LOOP
    CR
    0 11 1 DO I 3 .R ." : " TEST-NB-KEYS I CELLS + @ DUP 6 .R I * + DUP SPACE 6 .R CR LOOP DROP ;

TEST-KEYS /HASH-TABLE ERASE
FILL-TABLE
.TABLE

: INSERT-TABLE
    S" test/communes.txt" R/O OPEN-FILE THROW
    >R 0
    BEGIN
        LINE-BUFFER 256 R@ READ-LINE THROW WHILE
        DUP IF
            SWAP 1+ DUP ROT LINE-BUFFER SWAP INSERT-RECORD
        ELSE
            DROP
        THEN
    REPEAT DROP
    R> CLOSE-FILE THROW DROP ;

INSERT-TABLE
S" blogolo" FIND-RECORD 0 ?S
S" amiens" FIND-RECORD DUP RECORD-NAME COUNT S" amiens" ?STR RECORD-INDEX 343 ?S
S" arras" FIND-RECORD DUP RECORD-NAME COUNT S" arras" ?STR RECORD-INDEX 747 ?S
S" parzac" FIND-RECORD DUP RECORD-NAME COUNT S" parzac" ?STR RECORD-INDEX 11703 ?S
HEAP-FREE
BYE
