
50000 CONSTANT M
VARIABLE N
4 CELLS CONSTANT NODE-SIZE 
7 CONSTANT NUMBER-SIZE
NUMBER-SIZE M * CONSTANT LINE%
CREATE LINE LINE% ALLOT

: MAIN 
    BEGIN
        LINE LINE% STDIN READ-LINE THROW 
        WHILE
        LINE SWAP TYPE BL EMIT CR
    REPEAT ;

MAIN BYE
