REQUIRE ffl/tst.fs
REQUIRE hash-table.fs

." TEST HASH-TABLE" CR

T{
    1024 CREATE-HASH-TABLE MY-TABLE

    4807 S" foo" MY-TABLE ADD-HASH-TABLE-RECORD
    2312 S" bar" MY-TABLE ADD-HASH-TABLE-RECORD
    42   S" qux" MY-TABLE ADD-HASH-TABLE-RECORD
    BYE

    S" qux" MY-TABLE FIND-HASH-TABLE-RECORD ?TRUE @ 42   ?S
    S" foo" MY-TABLE FIND-HASH-TABLE-RECORD ?TRUE @ 4807 ?S
    S" bar" MY-TABLE FIND-HASH-TABLE-RECORD ?TRUE @ 2312 ?S

    MY-TABLE FREE-RECORDS-SPACE
}T

