REQUIRE ffl/tst.fs
REQUIRE records.fs
REQUIRE linked-list.fs

." TEST LINKED-LIST" CR

T{
    1024 CREATE-RECORDS-SPACE MY-LINKS
    4807 NIL MY-LINKS ADD-LINK
    2317 SWAP MY-LINKS ADD-LINK
    42   SWAP MY-LINKS ADD-LINK
    2@ SWAP 42   ?S
    2@ SWAP 2317 ?S
    2@ SWAP 4807 ?S
    NIL ?S
    MY-LINKS FREE-RECORDS-SPACE
}T
