REQUIRE ffl/tst.fs
REQUIRE priority-queue.fs

." PRIORITY-QUEUE" CR

T{
    1024 DUP * HEAP-ALLOCATE

    S" foo" 4 INSERT-VERTEX
    S" bar" 2 INSERT-VERTEX
    S" qux" 1 INSERT-VERTEX


    S" foo" FIND-VERTEX 40 UPDATE-PRIORITY
    S" foo" FIND-VERTEX VERTEX->PRIORITY 1 ?S
    S" bar" FIND-VERTEX 20 UPDATE-PRIORITY
    S" qux" FIND-VERTEX 10 UPDATE-PRIORITY
    S" foo" FIND-VERTEX 05 UPDATE-PRIORITY
    QUEUE @ 3 ?S
    EXTRACT-MIN DUP VERTEX->TOTAL-COST 05 ?S
                    VERTEX->NAME S" foo" ?STR
    EXTRACT-MIN DUP VERTEX->TOTAL-COST 10 ?S
                    VERTEX->NAME S" qux" ?STR
    EXTRACT-MIN DUP VERTEX->TOTAL-COST 20 ?S
                    VERTEX->NAME S" bar" ?STR
    HEAP-FREE
}T
