REQUIRE ffl/tst.fs
REQUIRE graph.fs

." TEST GRAPH" CR

T{
    10000 GRAPH MY-GRAPH
    S" foo" MY-GRAPH ADD-VERTEX
    S" bar" MY-GRAPH ADD-VERTEX
    S" foo" MY-GRAPH FIND-VERTEX ?TRUE
    2317 4807 ROT 2!
    S" bar" MY-GRAPH FIND-VERTEX ?TRUE
    42 65 ROT 2!
    1 MY-GRAPH VERTEX^ 2@   65 ?S   42 ?S
    0 MY-GRAPH VERTEX^ 2@ 4807 ?S 2317 ?S
    MY-GRAPH FREE-GRAPH
}T
