REQUIRE ffl/tst.fs
REQUIRE linked-list.fs

." TEST LINKED-LIST" CR

T{
    1024 DUP * HEAP-ALLOCATE
    VARIABLE MY-LIST
    NIL MY-LIST !
    4807 MY-LIST ADD-LINK
    2317 MY-LIST ADD-LINK
    42   MY-LIST ADD-LINK

    MY-LIST @ LINK>ITEM 42 ?S
    MY-LIST @ LINK>NEXT LINK>ITEM 2317 ?S
    MY-LIST @ LINK>NEXT LINK>NEXT LINK>ITEM 4807 ?S

    HEAP-FREE
}T
