REQUIRE ffl/tst.fs
REQUIRE vertex.fs
REQUIRE graph.fs

." TEST GRAPH" CR

T{
    16384 DUP * HEAP-ALLOCATE

    VERTICE OFF
    QUEUE OFF

    HEAP-HERE . CR
    S" gdansk" 2 INSERT-VERTEX
    0 VERTEX^ @ VERTEX->#EDGES 2 ?S
    0 VERTEX^ @ VERTEX->NAME S" gdansk" ?STR
    1 100 0 0 VERTEX^ @ SET-EDGE
    2 300 1 0 VERTEX^ @ SET-EDGE
    0 VERTEX^ @ EDGE-LIMITS
    DUP EDGE->COST 100 ?S
    CELL+ EDGE->COST 300 ?S
    0 VERTEX^ @ VERTEX->EDGES CELL+
    DUP EDGE->DESTINATION 2 ?S
    DUP EDGE->COST 300 ?S
    S" bydgoszcz" 3 INSERT-VERTEX
    0 100 0 1 VERTEX^ SET-EDGE
    2 100 1 1 VERTEX^ SET-EDGE
    3 400 2 1 VERTEX^ SET-EDGE
    1 VERTEX^ VERTEX->EDGES
    DUP EDGE->DESTINATION 0 ?S
    DUP EDGE->COST 100 ?S
    S" torun" 3 INSERT-VERTEX
    0 300 0 2 VERTEX^ SET-EDGE
    1 100 1 2 VERTEX^ SET-EDGE
    3 100 2 2 VERTEX^ SET-EDGE
    S" warszawa" 2 INSERT-VERTEX
    1 400 0 3 VERTEX^ SET-EDGE
    2 100 1 3 VERTEX^ SET-EDGE

    S" gdansk" FIND-VERTEX  S" warszawa" FIND-VERTEX
    PATH-COST 300 ?S
    S" bydgoszcz" FIND-VERTEX   S" warszawa" FIND-VERTEX
    PATH-COST 200 ?S
    HEAP-FREE
}T
