REQUIRE ffl/tst.fs
REQUIRE hash-table.fs

." TEST HASH-TABLE" CR

T{
    1024 1024 CREATE-HASH-TABLE MY-TABLE

    4807 S" foo" MY-TABLE ADD-HT-RECORD
    2312 S" bar" MY-TABLE ADD-HT-RECORD
    42   S" qux" MY-TABLE ADD-HT-RECORD

    S" qux" MY-TABLE FIND-HT-RECORD ?TRUE 42   ?S
    S" foo" MY-TABLE FIND-HT-RECORD ?TRUE 4807 ?S
    S" bar" MY-TABLE FIND-HT-RECORD ?TRUE 2312 ?S

    1 S" furmeyer" MY-TABLE ADD-HT-RECORD
    2 S" mennecy"  MY-TABLE ADD-HT-RECORD
    3 S" salazac"  MY-TABLE ADD-HT-RECORD

    S" mennecy"      MY-TABLE FIND-HT-RECORD ?TRUE 2 ?S
    S" salazac"      MY-TABLE FIND-HT-RECORD ?TRUE 3 ?S
    S" furmeyer"     MY-TABLE FIND-HT-RECORD ?TRUE 1 ?S

    MY-TABLE FREE-RECORDS-SPACE
}T

