REQUIRE ffl/tst.fs
REQUIRE hash-table.fs

." TEST HASH-TABLE" CR

T{
    1024 HEX CREATE-HASH-TABLE MY-TABLE

    4807 S" foo" MY-TABLE ADD-HT-RECORD 
    2312 S" bar" MY-TABLE ADD-HT-RECORD
    42   S" qux" MY-TABLE ADD-HT-RECORD

    S" qux" MY-TABLE DBG FIND-HT-RECORD ?TRUE @ 42   ?S
    S" foo" MY-TABLE FIND-HT-RECORD ?TRUE @ 4807 ?S
    S" bar" MY-TABLE FIND-HT-RECORD ?TRUE @ 2312 ?S

    MY-TABLE FREE-RECORDS-SPACE
}T

