REQUIRE ffl/tst.fs
REQUIRE priority-queue.fs
REQUIRE random.fs

." TEST PRIORITY-QUEUE" CR

T{
    16384 DUP * HEAP-ALLOCATE

    VERTICE OFF

    S" foo" 4 INSERT-VERTEX
    S" bar" 2 INSERT-VERTEX
    S" qux" 1 INSERT-VERTEX

    VERTICE @ 3 ?S

    VERTICE-INIT
    S" foo" FIND-VERTEX 400 OVER VERTEX->TOTAL-COST!
    UPDATE-PRIORITY
    1 ITEM^ @ VERTEX->TOTAL-COST 400 ?S
    S" bar" FIND-VERTEX 250 OVER VERTEX->TOTAL-COST!
    UPDATE-PRIORITY
    1 ITEM^ @ VERTEX->TOTAL-COST 250 ?S
    S" qux" FIND-VERTEX 025 OVER VERTEX->TOTAL-COST!
    UPDATE-PRIORITY
    1 ITEM^ @ VERTEX->TOTAL-COST 25 ?S
    S" foo" FIND-VERTEX 2 OVER VERTEX->TOTAL-COST!
    UPDATE-PRIORITY
    1 ITEM^ @ VERTEX->TOTAL-COST 2 ?S
}T
    : >STR ( n -- addr,count )
        0 <# #S #> ;

    : SETUP-LOOP ( n -- )
        0 DO
            I >STR 0 INSERT-VERTEX
        LOOP ;

    : UPDATE-LOOP
        VERTICE @ 0 DO
            I VERTEX^
            RND 10000 MOD
            OVER VERTEX->TOTAL-COST!
            UPDATE-PRIORITY
        LOOP ;

    VARIABLE MIN-COST

    : CHECK-LOOP
        -1 MIN-COST !
        QUEUE @ 0 DO
            EXTRACT-MIN VERTEX->TOTAL-COST
            MIN-COST @ OVER <= ?TRUE
            MIN-COST !
        LOOP ;


T{
    QUEUE OFF
    VERTICE OFF
    10000 SETUP-LOOP
}T
T{
    VERTICE-INIT
}T
T{
    UPDATE-LOOP
}T
T{
    CHECK-LOOP
}T
    HEAP-FREE
}T
