REQUIRE ffl/tst.fs
REQUIRE vertex.fs

." TEST VERTEX" CR

T{
    17
    2 SWAP PQ-INDEX!
    4807 SWAP TOTAL-COST!
    VISIT!
    DUP VISITED ?TRUE
    UNVISIT!
    DUP VISITED ?FALSE
    DUP PQ-INDEX 2 ?S
    DUP #EDGES 17 ?S
    TOTAL-COST 4807 ?S

    S" foo" STR-HEAP, 4 ADD-VERTEX
    DUP @ COUNT S" foo" ?STR
    CELL+ @ 4 ?S
}T
