\ ------- julka.fs --------

CREATE KLAUDIA-SURPLUS BN-SIZE ALLOT
CREATE KLAUDIA-APPLES BN-SIZE ALLOT
CREATE NATALIA-APPLES BN-SIZE ALLOT
CREATE TOTAL-APPLES BN-SIZE ALLOT
CREATE TEMP BN-SIZE ALLOT

: COMPUTE-APPLES
    TOTAL-APPLES KLAUDIA-SURPLUS TEMP BN+
    TEMP KLAUDIA-APPLES BN2/
    TOTAL-APPLES KLAUDIA-APPLES NATALIA-APPLES BN- ;

: PROCESS-TEST-CASE
    READ-INPUT-LINE ASSERT( )
    TOTAL-APPLES STR>BN
    READ-INPUT-LINE ASSERT( )
    KLAUDIA-SURPLUS STR>BN
    COMPUTE-APPLES
    KLAUDIA-APPLES BN>STR TYPE CR
    NATALIA-APPLES BN>STR TYPE CR ;

: PROCESS
    10 0 DO
        PROCESS-TEST-CASE
    LOOP ;


