REQUIRE random.fs

320 CONSTANT MAX-LINE
CREATE LINE MAX-LINE 3 + ALLOT
VARIABLE LINE-LENGTH

CHAR 1 CONSTANT PAWN
CHAR 0 CONSTANT SQUARE

: UNTAKE ( i,dir -- )
    LINE >R 2DUP + DUP ROT +
    R@ + PAWN SWAP C!
    R@ + PAWN SWAP C!
    R> + SQUARE SWAP C! ;

: FIT? ( i,dir -- f )
    LINE >R 2DUP + DUP ROT +
    R@ + C@ SQUARE =
    SWAP R@ + C@ SQUARE = AND
    SWAP R> + C@ PAWN = AND ;

: RANDOM-DIR ( -- 1|-1 )
    2 RANDOM IF -1 ELSE 1 THEN ;

: UNTAKE-MAYBE ( i -- )
    RANDOM-DIR 2DUP FIT? IF UNTAKE THEN ;

: RANDOM-PAWNS ( -- p1,p2,n )
    LINE-LENGTH @ RANDOM
    RANDOM 2 IF LINE-LENGTH @ RANDOM ELSE DUP THEN
    2DUP - ABS 3 < IF DROP 1 ELSE 2 THEN ;

: GENERATE-INITIAL 
    MAX-LINE 3 - RANDOM 3 + LINE-LENGTH !
    LINE LINE-LENGTH @ SQUARE FILL
    RANDOM-PAWNS DUP >R 0 DO
        LINE + PAWN SWAP C!
    LOOP R> ;

: GENERATE-UNTAKE ( -- f )
    FALSE
    LINE-LENGTH @ 2 - 2 2DUP > IF
        DO
            I RANDOM-DIR
            2DUP FIT? IF
                UNTAKE DROP TRUE
            ELSE
                2DROP
            THEN
        LOOP
    ELSE
        2DROP
    THEN ;

: GENERATE-UNTAKES
    TRUE
    BEGIN
        WHILE
        GENERATE-UNTAKE
    REPEAT ;

: GENERATE-LINE
    GENERATE-INITIAL
    GENERATE-UNTAKES
    [CHAR] S EMIT [CHAR] " EMIT SPACE 
    LINE LINE-LENGTH @ TYPE [CHAR] " EMIT SPACE
    ." LONER? " 2 = IF ." ?FALSE" ELSE ." ?TRUE" THEN CR ;

: GENERATE-TESTS
    ." FPATH PATH+ src" CR
    ." FPATH PATH+ test" CR
    ." REQUIRE ffl/tst.fs" CR
    ." REQUIRE parser.fs" CR
    ." REQUIRE loner.fs" CR
    CR
    UTIME DROP SEED !
    100 0 DO GENERATE-LINE LOOP ;

GENERATE-TESTS BYE

