
\ -------- input.fs ------------

65535 CONSTANT LINE-MAX

CREATE LINE-BUFFER LINE-MAX ALLOT


VARIABLE INPUT-FILE

: OPEN-INPUT-FILE ( addr,count -- )
    R/O OPEN-FILE THROW INPUT-FILE ! ;

: CLOSE-INPUT-FILE
    INPUT-FILE @ CLOSE-FILE THROW ;

: READ-INPUT-LINE ( -- addr,count,flag )
    LINE-BUFFER DUP LINE-MAX
    INPUT-FILE @ READ-LINE THROW ;

: PROCESS-TEST-CASE ( n -- )
    READ-INPUT-LINE ASSERT( )
    STR-TOKENS ASSERT( 1 = )
    STR>NUMBER >R
    READ-INPUT-LINE ASSERT( )
    DUP R> ASSERT( = )
    LONER EXECUTE IF
        ." yes"
    ELSE
        ." no"
    THEN CR 2DROP ;




