\ --------- loner.fs --------

CHAR 1 CHAR-PARSER ONE
CHAR 0 CHAR-PARSER ZERO

' ONE ' ONE SEQUENCE ELEVEN
' ONE ' ZERO SEQUENCE TEN
' ZERO ' ONE SEQUENCE ZERO-ONE
' ZERO ' ZERO SEQUENCE ZERO-ZERO

' ZERO-ONE REPETITION ZERO-ONES
' ELEVEN REPETITION ELEVENS
' TEN REPETITION TENS


: LONER-A
    ONE ;


' ELEVEN ' ZERO SEQUENCE LONER-B

' ZERO REPETITION ZEROES


' LONER-A ' LONER-B ALTERNATIVE LONER-A-OR-B

' ZEROES ' LONER-A-OR-B SEQUENCE PREFIX-LONER

' ZEROES ' EOS SEQUENCE SUFFIX-LONER

' PREFIX-LONER ' SUFFIX-LONER SEQUENCE LONER
    
