
1000 CONSTANT MAXBYTES

CREATE BIGINT MAXBYTES ALLOT 

\ sets the big int to 1
: INITIALIZE ( -- )
    BIGINT MAXBYTES ERASE
    BIGINT MAXBYTES 1- +
    1 SWAP C! ;

: PRINT-BIGINT 
    BIGINT -1
    BEGIN
        1+
        OVER OVER + C@ 
    UNTIL  \ adr,p
    DUP ROT + SWAP
    MAXBYTES SWAP - TYPE ;

: MULTIPLY-BIGINT ( n -- )
    
: FACTORIAL ;

\ read a number on stdin, assume no exception
: READ-INT ( -- addr,l )
    PAD DUP 40 STDIN READ-LINE THROW DROP 
    S>NUMBER? DROP DROP ;

: MAIN
    READ-INT 0 DO 
        READ-INT FACTORIAL . CR 
    LOOP ;

INITIALIZE
BIGINT 999 + CHAR 7 SWAP C!
BIGINT 998 + CHAR 0 SWAP C!
BIGINT 997 + CHAR 8 SWAP C!
BIGINT 996 + CHAR 4 SWAP C!
BIGINT 995 + CHAR 7 SWAP C!
BIGINT 994 + CHAR 0 SWAP C!
BIGINT 993 + CHAR 8 SWAP C!
BIGINT 993 + CHAR 4 SWAP C!

PRINT-BIGINT
BYE
