50000 CONSTANT M
CHAR 0 CONSTANT ZERO
CHAR 9 CONSTANT NINE
CHAR - CONSTANT MINUS
VARIABLE N
VARIABLE Q
CREATE NS M CELLS ALLOT

: GOBBLE ( -- c )
    BEGIN KEY DUP ZERO < OVER MINUS <> AND WHILE DROP REPEAT ;

: IS-DIGIT? ( c -- f )
    DUP ZERO >= SWAP NINE <= AND ;

: GET-NUMBER ( c -- acc ) 
    GOBBLE
    DUP MINUS = IF DROP KEY -1 ELSE 0 THEN SWAP
    0 SWAP
    BEGIN DUP IS-DIGIT? WHILE ZERO - SWAP 10 * + KEY REPEAT DROP SWAP IF NEGATE THEN ;

: GET-NUMBERS
    GET-NUMBER DUP N !
    0 DO
        GET-NUMBER NS I CELLS + !
    LOOP ;

: GET-QUERY ( -- y,x )
    GET-NUMBER GET-NUMBER SWAP ;

: DO-QUERIES
    GET-NUMBER 0 DO
        GET-QUERY .s CR
    LOOP ;

: PRINT-NUMBERS 
    N @ 0 DO
        NS I CELLS + @ . 
    LOOP CR ;
PAGE
GET-NUMBERS DO-QUERIES
BYE
